export interface EmergencyContact {
  id: string;
  title: string;
  agency: string;
  number: string;
  tollFree?: string;
  category: "National" | "Legal Aid" | "Women & Kids" | "Valenzuela" | "Labor & Rights";
  desc: string;
  icon: string;
  coverage: string;
  availableHours: string;
}

export const PHILIPPINE_EMERGENCY_CONTACTS: EmergencyContact[] = [
  // National
  {
    id: "e911",
    title: "National Emergency Hotline (E911)",
    agency: "Emergency 911 National Executive Commission",
    number: "911",
    category: "National",
    desc: "Centralized nationwide dispatch for Police, Fire, Ambulance, and Medical Rescue.",
    icon: "call",
    coverage: "Nationwide (Philippines)",
    availableHours: "24/7",
  },
  {
    id: "pnp-natl",
    title: "PNP National Operations Center",
    agency: "Philippine National Police (PNP)",
    number: "117",
    tollFree: "(02) 8722-0650",
    category: "National",
    desc: "Immediate police assistance, crime reporting, and emergency patrol dispatch.",
    icon: "shield",
    coverage: "Nationwide",
    availableHours: "24/7",
  },
  {
    id: "prc-143",
    title: "Philippine Red Cross Helpline",
    agency: "Philippine Red Cross (PRC)",
    number: "143",
    tollFree: "(02) 8790-2300",
    category: "National",
    desc: "Emergency ambulance response, blood bank requests, and disaster relief.",
    icon: "medkit",
    coverage: "Nationwide",
    availableHours: "24/7",
  },
  {
    id: "bfp-fire",
    title: "Bureau of Fire Protection (BFP)",
    agency: "Department of the Interior and Local Government",
    number: "(02) 8426-0219",
    category: "National",
    desc: "Fire emergencies, rescue operations, hazardous materials, and building safety.",
    icon: "flame",
    coverage: "Metro Manila & Nationwide",
    availableHours: "24/7",
  },
  {
    id: "ndrrmc",
    title: "NDRRMC Operations Center",
    agency: "National Disaster Risk Reduction & Management Council",
    number: "(02) 8911-1406",
    category: "National",
    desc: "Typhoon rescue, flood evacuation, earthquake alerts, and disaster monitoring.",
    icon: "warning",
    coverage: "Nationwide",
    availableHours: "24/7",
  },

  // Legal Aid & Rights
  {
    id: "pao-inquest",
    title: "Public Attorney's Office (PAO Inquest)",
    agency: "Department of Justice (DOJ)",
    number: "(02) 8929-9436",
    tollFree: "0939-323-3665",
    category: "Legal Aid",
    desc: "Free 24/7 legal counsel for inquest proceedings, custodial investigations, and indigent citizens.",
    icon: "shield-checkmark",
    coverage: "Nationwide / NCR Inquest",
    availableHours: "24/7 Hotline",
  },
  {
    id: "chr-rights",
    title: "Commission on Human Rights (CHR)",
    agency: "CHR National Citizen Investigation",
    number: "(02) 8928-5655",
    tollFree: "0920-509-9940",
    category: "Legal Aid",
    desc: "Investigation of illegal arrest, custodial torture, arbitrary detention, and human rights violations.",
    icon: "hand-left",
    coverage: "Nationwide",
    availableHours: "24/7 Quick Response",
  },
  {
    id: "ibp-legalaid",
    title: "IBP National Legal Aid",
    agency: "Integrated Bar of the Philippines",
    number: "(02) 8631-3014",
    category: "Legal Aid",
    desc: "Free legal consultations, court appearances for qualified indigents, and legal referral.",
    icon: "briefcase",
    coverage: "Nationwide Chapters",
    availableHours: "Mon-Fri 8AM-5PM",
  },
  {
    id: "doj-action",
    title: "DOJ Action Center (DOJAC)",
    agency: "Department of Justice",
    number: "(02) 8521-1614",
    category: "Legal Aid",
    desc: "Legal counseling, complaints against prosecutors, mediation, and victim legal aid.",
    icon: "document-text",
    coverage: "Nationwide",
    availableHours: "Mon-Fri 8AM-5PM",
  },

  // Women, Children & Family
  {
    id: "pnp-wcpc",
    title: "PNP Women & Children Protection Center",
    agency: "Philippine National Police (WCPC)",
    number: "(02) 8532-6690",
    tollFree: "0919-777-7377",
    category: "Women & Kids",
    desc: "VAWC (RA 9262), domestic violence, sexual assault, and child protection desk.",
    icon: "heart",
    coverage: "Nationwide",
    availableHours: "24/7 Crisis Response",
  },
  {
    id: "dswd-crisis",
    title: "DSWD Crisis Intervention (CIU)",
    agency: "Department of Social Welfare and Development",
    number: "16545",
    tollFree: "(02) 8962-2813",
    category: "Women & Kids",
    desc: "Protective custody for abused women/children, emergency financial aid, and shelter.",
    icon: "people",
    coverage: "Nationwide",
    availableHours: "24/7",
  },
  {
    id: "bantay-bata",
    title: "Bantay Bata 163",
    agency: "Child Protection Program",
    number: "163",
    tollFree: "0917-814-7227",
    category: "Women & Kids",
    desc: "Reporting child abuse, exploitation, child trafficking, and emergency rescue.",
    icon: "happy",
    coverage: "Nationwide",
    availableHours: "24/7",
  },
  {
    id: "iacat-trafficking",
    title: "IACAT Action Line Against Trafficking",
    agency: "Inter-Agency Council Against Trafficking",
    number: "1343",
    tollFree: "(02) 8527-3467",
    category: "Women & Kids",
    desc: "Human trafficking, illegal recruitment, online sexual exploitation of children (OSEC).",
    icon: "lock-closed",
    coverage: "Nationwide / Overseas",
    availableHours: "24/7",
  },

  // Valenzuela City Local
  {
    id: "val-drrmo",
    title: "Valenzuela Disaster & Emergency (VCDRRMO)",
    agency: "City Government of Valenzuela",
    number: "(02) 8352-5000",
    tollFree: "(02) 8292-1405",
    category: "Valenzuela",
    desc: "Valenzuela City local central rescue, ambulance, typhoon flood response, and dispatch.",
    icon: "business",
    coverage: "Valenzuela City",
    availableHours: "24/7 Central Command",
  },
  {
    id: "val-police",
    title: "Valenzuela City Police Station",
    agency: "PNP Northern Police District (NPD)",
    number: "(02) 8352-4000",
    tollFree: "0917-816-5278",
    category: "Valenzuela",
    desc: "Local police headquarters in Poblacion & substation hotlines across all barangays.",
    icon: "shield",
    coverage: "Valenzuela City",
    availableHours: "24/7",
  },
  {
    id: "val-fire",
    title: "Valenzuela City Fire Station",
    agency: "BFP Valenzuela City",
    number: "(02) 8352-2000",
    tollFree: "(02) 8292-3519",
    category: "Valenzuela",
    desc: "Direct fire station dispatch across Karuhatan, Malinta, Marulas, and Gen. T. de Leon.",
    icon: "flame",
    coverage: "Valenzuela City",
    availableHours: "24/7",
  },
  {
    id: "val-redcross",
    title: "Philippine Red Cross - Valenzuela Chapter",
    agency: "PRC Valenzuela City Chapter",
    number: "(02) 8352-1000",
    category: "Valenzuela",
    desc: "Local ambulance service, blood center, and disaster preparedness in Valenzuela.",
    icon: "medkit",
    coverage: "Valenzuela City",
    availableHours: "24/7",
  },

  // Labor, OFW & Citizen Rights
  {
    id: "dole-1349",
    title: "DOLE Labor Hotline",
    agency: "Department of Labor and Employment",
    number: "1349",
    category: "Labor & Rights",
    desc: "Immediate labor grievance, illegal dismissal, withheld 13th month pay, and SEnA filing.",
    icon: "construct",
    coverage: "Nationwide",
    availableHours: "24/7",
  },
  {
    id: "dmw-ofw",
    title: "DMW / OWWA OFW Crisis Center",
    agency: "Department of Migrant Workers",
    number: "1348",
    tollFree: "(02) 8722-1144",
    category: "Labor & Rights",
    desc: "Emergency repatriation, distressed OFWs abroad, illegal recruitment, and legal assistance.",
    icon: "airplane",
    coverage: "OFWs Worldwide & PH",
    availableHours: "24/7",
  },
  {
    id: "dti-consumer",
    title: "DTI Consumer Protection Hotline",
    agency: "Department of Trade and Industry",
    number: "1-384",
    tollFree: "0917-834-3330",
    category: "Labor & Rights",
    desc: "Consumer rights, online scams, price gouging, defective products, and warranty disputes.",
    icon: "cart",
    coverage: "Nationwide",
    availableHours: "Mon-Sun 8AM-5PM",
  },
  {
    id: "npc-privacy",
    title: "National Privacy Commission (NPC)",
    agency: "National Privacy Commission",
    number: "(02) 8234-2228",
    category: "Labor & Rights",
    desc: "Data privacy breach, online lending app harassment, leaked personal identification.",
    icon: "finger-print",
    coverage: "Nationwide",
    availableHours: "Mon-Fri 8AM-5PM",
  },
];
