/**
 * Mock data for attorneys around Valenzuela City and nearby CAMANAVA area.
 */
import type { AreaAttorney } from "./types";

export const LOCAL_VALENZUELA_ATTORNEYS: AreaAttorney[] = [
  {
    id: "v-att-1",
    name: "Atty. Carlos Mendoza",
    title: "Senior Partner, Mendoza & Partners Law",
    officeAddress: "2F Mendoza Commercial Bldg, MacArthur Highway, Karuhatan",
    barangay: "Karuhatan",
    city: "Valenzuela City",
    distanceKm: 0.8,
    specialty: "Labor Law & Civil Litigation",
    category: "Labor & DOLE",
    experienceYears: 13,
    rating: 4.9,
    reviewsCount: 78,
    ibpChapter: "IBP CalMANA Chapter",
    isAvailable: true,
    nextSlot: "Today, 3:00 PM",
    supportedModes: ["office", "video", "phone"],
    about:
      "Atty. Carlos Mendoza has represented workers and small enterprise owners in Valenzuela City for over 13 years. He handles labor claims, SEnA mediation, illegal dismissal cases, and general civil dispute settlements.",
  },
  {
    id: "v-att-2",
    name: "Atty. Elena Bautista-Santos",
    title: "Lead Counsel, Bautista Family & Legal Services",
    officeAddress: "Unit 304, Puregold Building, McArthur Highway, Dalandanan",
    barangay: "Dalandanan",
    city: "Valenzuela City",
    distanceKm: 1.2,
    specialty: "Family Code, Support & Annulment",
    category: "Family & Civil",
    experienceYears: 16,
    rating: 5.0,
    reviewsCount: 112,
    ibpChapter: "IBP CalMANA Chapter",
    isAvailable: true,
    nextSlot: "Tomorrow, 10:30 AM",
    supportedModes: ["office", "video", "phone"],
    about:
      "Specializing in Philippine family law, domestic relations, adoption, and child custody. Atty. Bautista provides compassionate guidance to families in Valenzuela and Northern Metro Manila.",
  },
  {
    id: "v-att-3",
    name: "Atty. Jonathan Reyes",
    title: "Managing Attorney, Reyes Defense & Trial Office",
    officeAddress: "3F City Hall Commercial Center, MacArthur Hwy, Malinta",
    barangay: "Malinta",
    city: "Valenzuela City",
    distanceKm: 1.6,
    specialty: "Criminal Defense, Inquest & Bail",
    category: "Criminal Defense",
    experienceYears: 10,
    rating: 4.8,
    reviewsCount: 64,
    ibpChapter: "IBP CalMANA Chapter",
    isAvailable: false,
    nextSlot: "Monday, 2:00 PM",
    supportedModes: ["office", "video"],
    about:
      "Located just minutes away from the Valenzuela City Hall of Justice, Atty. Reyes provides zealous criminal defense representation from inquest proceedings to regional trial court litigation.",
  },
  {
    id: "v-att-4",
    name: "Atty. Patricia Dizon",
    title: "Principal, Dizon Real Estate & Corporate Law",
    officeAddress: "Unit 12, G. Marcelo St., Maysan Road, Malinta",
    barangay: "Malinta",
    city: "Valenzuela City",
    distanceKm: 2.1,
    specialty: "Land Titles, Transfer & Real Estate",
    category: "Real Estate & Land",
    experienceYears: 12,
    rating: 4.9,
    reviewsCount: 89,
    ibpChapter: "IBP CalMANA Chapter",
    isAvailable: true,
    nextSlot: "Today, 4:30 PM",
    supportedModes: ["office", "video", "phone"],
    about:
      "Atty. Dizon assists residents and developers in Valenzuela with land title verification, deed of absolute sale, transfer of ownership, extrajudicial settlements, and property boundary disputes.",
  },
  {
    id: "v-att-5",
    name: "Atty. Manuel Santiago",
    title: "Partner, Santiago & Associates",
    officeAddress: "22 Gen. T. de Leon Avenue, near NLEX Overpass",
    barangay: "Gen. T. de Leon",
    city: "Valenzuela City",
    distanceKm: 2.7,
    specialty: "Commercial Law & Business Contracts",
    category: "Corporate & Business",
    experienceYears: 15,
    rating: 4.7,
    reviewsCount: 52,
    ibpChapter: "IBP CalMANA Chapter",
    isAvailable: true,
    nextSlot: "Tomorrow, 1:00 PM",
    supportedModes: ["office", "video"],
    about:
      "Serves local factories, businesses, and commercial establishments in Gen. T. de Leon and Ugong with corporate governance, municipal licensing, supplier contracts, and tax compliance.",
  },
  {
    id: "v-att-6",
    name: "Atty. Rosalie Fernandez",
    title: "Senior Counsel, Fernandez Legal Clinic",
    officeAddress: "45 Dr. J.P. Rizal St., Poblacion, Polo",
    barangay: "Poblacion / Polo",
    city: "Valenzuela City",
    distanceKm: 3.4,
    specialty: "Barangay Disputes & Civil Law",
    category: "Family & Civil",
    experienceYears: 8,
    rating: 4.9,
    reviewsCount: 41,
    ibpChapter: "IBP CalMANA Chapter",
    isAvailable: true,
    nextSlot: "Tomorrow, 3:30 PM",
    supportedModes: ["office", "phone"],
    about:
      "Focuses on community mediation, notarization, small claims preparation, and amicable settlement of civil disputes in the historical district of Polo, Valenzuela.",
  },
];
